SELECT * FROM CITY WHERE COUNTRYCODE=’USA’ AND POPULATION > 100000;


SELECT NAME FROM CITY WHERE COUNTRYCODE=’USA’ AND POPULATION > 120000;


SELECT * FROM CITY


SELECT * FROM CITY WHERE ID=1661


SELECT * FROM CITY WHERE COUNTRYCODE='JPN'


SELECT NAME FROM CITY WHERE COUNTRYCODE='JPN'


SELECT CITY, STATE FROM STATION;


SELECT DISTINCT CITY FROM STATION WHERE ID%2=0;


SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION ;


SELECT DISTINCT(CITY) FROM STATION WHERE REGEXP_LIKE(CITY, '[aiueo]$') ORDER BY CITY;


SELECT DISTINCT CITY FROM STATION WHERE (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%') AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u') ORDER BY CITY;


SELECT DISTINCT CITY FROM STATION WHERE UPPER(SUBSTR(CITY,1,1)) NOT IN ('A','E','I','O','U') AND LOWER(SUBSTR(CITY,1,1)) NOT IN ('a','e','i','o','u');


SELECT DISTINCT CITY FROM STATION WHERE UPPER(SUBSTR(CITY,LENGTH(CITY),1)) NOT IN ('A','E','I','O','U') AND LOWER(SUBSTR(CITY,LENGTH(CITY),1)) NOT IN ('a','e','i','o','u');


SELECT DISTINCT CITY FROM STATION WHERE LOWER(SUBSTR(CITY,1,1)) NOT IN ('a','e','i','o','u') AND LOWER(SUBSTR(CITY,LENGTH(CITY),1)) NOT IN ('a','e','i','o','u');   


SELECT DISTINCT CITY FROM STATION WHERE LOWER(SUBSTR(CITY,1,1)) NOT IN ('a','e','i','o','u') OR LOWER(SUBSTR(CITY, LENGTH(CITY),1)) NOT IN ('a','e','i','o','u');  


SELECT DISTINCT CITY FROM STATION WHERE LOWER(SUBSTR(CITY,1,1)) NOT IN ('a','e','i','o','u') AND LOWER(SUBSTR(CITY,LENGTH(CITY),1)) NOT IN ('a','e','i','o','u');


SELECT NAME FROM STUDENTS WHERE MARKS > 75 ORDER BY SUBSTR(NAME, LENGTH(NAME)-2, 3), ID; 


SELECT NAME FROM EMPLOYEE ORDER BY NAME;


SELECT NAME FROM EMPLOYEE WHERE SALARY>2000 AND MONTHS<10;